/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Interface (void);
GtkWidget* create_windowajouter (void);
GtkWidget* create_windowmodifier (void);
GtkWidget* create_windowsupprimer (void);
GtkWidget* create_windowafficher (void);
GtkWidget* create_capteural (void);
GtkWidget* create_defectueuse (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fen_modif (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fen_rech_id (void);
GtkWidget* create_gestionouvrier (void);
GtkWidget* create_affichage (void);
GtkWidget* create_modification (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_interfaceprincipale (void);
GtkWidget* create_windowajout1 (void);
GtkWidget* create_windowediter (void);
GtkWidget* create_windowafficher1 (void);
GtkWidget* create_window5supprimer (void);
GtkWidget* create_calendrier (void);
GtkWidget* create_login (void);
GtkWidget* create_Erreur (void);
GtkWidget* create_interfaceadmin (void);
GtkWidget* create_ajoutlogin (void);
