/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Interface;
  GtkWidget *windowajouter;
  GtkWidget *windowmodifier;
  GtkWidget *windowsupprimer;
  GtkWidget *fenetre_ajout;
  GtkWidget *gestionouvrier;
  GtkWidget *interfaceprincipale;
  GtkWidget *login;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*Interface = create_Interface ();
  gtk_widget_show (Interface);
  fenetre_ajout = create_fenetre_ajout ();
  gtk_widget_show (fenetre_ajout);
  gestionouvrier = create_gestionouvrier ();
  gtk_widget_show (gestionouvrier);
  interfaceprincipale=create_interfaceprincipale ();
  gtk_widget_show (interfaceprincipale);*/
  login = create_login ();
  gtk_widget_show (login);
  /*windowajouter = create_windowajouter ();
  gtk_widget_show (windowajouter);
  windowmodifier = create_windowmodifier ();
  gtk_widget_show (windowmodifier);
  windowsupprimer = create_windowsupprimer ();
  gtk_widget_show (windowsupprimer);*/

  gtk_main ();
  return 0;
}

